---
- hosts: all
  tasks:
    - name: Apt update
      apt:  update_cache=yes
      
    - name: Upgrade all packages
      apt: upgrade=dist

    - name: Install base packages
      apt: name={{ item }} state=present
      with_items:
        - nano
        - vim
        - yum-utils
        - lsof
        - mlocate
        - git
        - zsh
        - curl
        - tmux
        - wget
        - net-tools
        - telnet
        - unzip
