# vim:syntax=ruby

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  # config.vm.network "private_network", ip: "10.1.1.20"
  # config.vm.hostname = "baselinehost"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "512"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ubuntutrusty.yml"
    ansible.sudo = true
  end
end
